# No name since it is not an Action by itself.

on:
  workflow_call:
    secrets:
      REGISTRY_USERNAME:
        required: true
      REGISTRY_TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Chechout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.REGISTRY_USERNAME}}
          password: ${{secrets.REGISTRY_TOKEN}}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{secrets.HUB_UNAME}}/go-app:latest
